packages:
  - 'packages/*'

catalog:
  '@babel/parser': '^7.28.0'
  '@babel/traverse': '^7.28.0'
  globby: '^16.0.0'
  '@types/babel__traverse': '^7.20.7'
  '@types/node': '^24.1.0'
  tsup: '^8.5.0'
  rimraf: '^6.0.1'
  vitest: '^4.0.0'
